# Generated by Django 3.2.23 on 2025-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_pipeline_extension', '0002_add_signals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionformatsupport',
            options={'ordering': ['priority', 'mime_type'], 'verbose_name': 'Conversion format support', 'verbose_name_plural': 'Conversion format supports'},
        ),
        migrations.AlterModelOptions(
            name='documentconversionmetadata',
            options={'verbose_name': 'Document conversion metadata', 'verbose_name_plural': 'Document conversion metadata'},
        ),
        migrations.RemoveField(
            model_name='documentconversionmetadata',
            name='metadata',
        ),
        migrations.AddField(
            model_name='documentconversionmetadata',
            name='conversion_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Conversion details'),
        ),
        migrations.AlterField(
            model_name='conversionformatsupport',
            name='converter_backend',
            field=models.CharField(max_length=50, verbose_name='Converter backend'),
        ),
        migrations.AlterField(
            model_name='conversionformatsupport',
            name='format_name',
            field=models.CharField(max_length=50, verbose_name='Format name'),
        ),
        migrations.AlterField(
            model_name='conversionformatsupport',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is enabled'),
        ),
        migrations.AlterField(
            model_name='conversionformatsupport',
            name='mime_type',
            field=models.CharField(max_length=100, unique=True, verbose_name='MIME type'),
        ),
        migrations.AlterField(
            model_name='documentconversionmetadata',
            name='conversion_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conversion completed'),
        ),
        migrations.AlterField(
            model_name='documentconversionmetadata',
            name='conversion_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conversion started'),
        ),
        migrations.AlterField(
            model_name='documentconversionmetadata',
            name='conversion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_started', 'Not started')], default='not_started', max_length=20, verbose_name='Conversion status'),
        ),
        migrations.AlterField(
            model_name='documentconversionmetadata',
            name='converter_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='Converter used'),
        ),
        migrations.AlterField(
            model_name='documentconversionmetadata',
            name='original_format',
            field=models.CharField(blank=True, max_length=100, verbose_name='Original format'),
        ),
        migrations.AlterField(
            model_name='documentconversionmetadata',
            name='preview_generated',
            field=models.BooleanField(default=False, verbose_name='Preview generated'),
        ),
    ]
