version: '3.9'

services:
  postgresql:
    image: postgres:12.10-alpine
    environment:
      POSTGRES_DB: mayan
      POSTGRES_USER: mayan
      POSTGRES_PASSWORD: mayandbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mayan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mayan"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass mayanredispassword
    volumes:
      - redis_data:/data
    networks:
      - mayan
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_PASS: mayanrabbitpass
      RABBITMQ_DEFAULT_VHOST: mayan
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mayan
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mayanedms/mayanedms:s4.3
    environment:
      MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayandbpass','USER':'mayan','HOST':'postgresql'}}"
      MAYAN_CELERY_BROKER_URL: amqp://mayan:mayanrabbitpass@rabbitmq:5672/mayan
      MAYAN_CELERY_RESULT_BACKEND: redis://:mayanredispassword@redis:6379/1
      MAYAN_LOCK_MANAGER_BACKEND: mayan.apps.lock_manager.backends.redis_lock.RedisLock
      MAYAN_LOCK_MANAGER_BACKEND_ARGUMENTS: "{'redis_url':'redis://:mayanredispassword@redis:6379/2'}"
    volumes:
      - app_data:/var/lib/mayan
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "80:8000"
    networks:
      - mayan

networks:
  mayan:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  app_data:
