#!/bin/bash
echo Activating virtual environment...
source /opt/mayan-edms/bin/activate
echo Virtual environment activated
echo Testing Django...
python3 -c import django
echo Applying migrations...
python3 manage.py migrate converter_pipeline_extension
echo Enabling converter extension...
python3 manage.py manage_converter_pipeline enable
echo Setup completed!
