# Generated by Django 3.2.14 for Analytics Transformation Feature 1.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_analytics_report_task'),
        ('organizations', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text='Organization this session belongs to',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='analytics_search_sessions',
                to='organizations.organization',
                verbose_name='Organization'
            ),
        ),
        migrations.AddField(
            model_name='assetevent',
            name='search_session_id',
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text='Links this event to a search session for search-to-find metrics',
                null=True,
                verbose_name='Search session ID'
            ),
        ),
    ]
