# Generated by Django 3.2.23 on 2025-10-24 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0008_add_webp_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='event',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download')], help_text='Type of access event', max_length=16),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IP address of the client'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='rendition',
            field=models.ForeignKey(blank=True, help_text='Rendition that was downloaded (for download events)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.generatedrendition'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='share_link',
            field=models.ForeignKey(help_text='Share link that was accessed', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='distribution.sharelink'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the access occurred'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string'),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='checksum',
            field=models.CharField(blank=True, help_text='File checksum (MD5 or SHA256)', max_length=128),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if generation failed'),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='file',
            field=models.FileField(blank=True, help_text='Generated rendition file', null=True, upload_to='renditions/distribution/'),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='preset',
            field=models.ForeignKey(help_text='Preset used to generate this rendition', on_delete=django.db.models.deletion.CASCADE, to='distribution.renditionpreset'),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='publication_item',
            field=models.ForeignKey(help_text='Publication item this rendition is for', on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='distribution.publicationitem'),
        ),
        migrations.AlterField(
            model_name='generatedrendition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Generation status', max_length=16),
        ),
        migrations.AlterField(
            model_name='publication',
            name='access_policy',
            field=models.CharField(choices=[('public', 'Public (token access)'), ('login', 'Login required'), ('both', 'Both public and login access')], default='public', help_text='Access policy for this publication', max_length=16),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='downloads_count',
            field=models.IntegerField(default=0, help_text='Total downloads count'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration date and time', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='max_downloads',
            field=models.IntegerField(blank=True, help_text='Maximum total downloads allowed', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(help_text='Owner of this publication', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='presets',
            field=models.ManyToManyField(blank=True, help_text='Rendition presets to generate', related_name='publications', to='distribution.RenditionPreset'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='recipient_lists',
            field=models.ManyToManyField(blank=True, help_text='Recipient lists for this publication', related_name='publications', to='distribution.RecipientList'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(help_text='Title of the publication', max_length=255),
        ),
        migrations.AlterField(
            model_name='publicationitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicationitem',
            name='document_file',
            field=models.ForeignKey(help_text='Document file to include in publication', on_delete=django.db.models.deletion.CASCADE, to='documents.documentfile'),
        ),
        migrations.AlterField(
            model_name='publicationitem',
            name='publication',
            field=models.ForeignKey(help_text='Publication this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='distribution.publication'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(help_text='Email address of the recipient', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='locale',
            field=models.CharField(blank=True, help_text='Preferred language locale (e.g., en, ru)', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the recipient', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='internal_users',
            field=models.ManyToManyField(blank=True, help_text='Internal users in this list', related_name='distribution_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='name',
            field=models.CharField(help_text='Name of the recipient list', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='owner',
            field=models.ForeignKey(help_text='Owner of this list', on_delete=django.db.models.deletion.CASCADE, related_name='owned_recipient_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipientlist',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='External recipients in this list', related_name='recipient_lists', to='distribution.Recipient'),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this preset'),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='format',
            field=models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP'), ('tiff', 'TIFF'), ('pdf', 'PDF'), ('mp4', 'MP4')], help_text='Output format', max_length=16),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='height',
            field=models.IntegerField(blank=True, help_text='Maximum height in pixels (None for auto)', null=True),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='name',
            field=models.CharField(help_text='Unique name for this preset', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='quality',
            field=models.IntegerField(blank=True, help_text='Quality setting (0-100 for images, None for others)', null=True),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='resource_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of resource this preset applies to', max_length=32),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='watermark',
            field=models.JSONField(blank=True, default=dict, help_text='Watermark settings as JSON'),
        ),
        migrations.AlterField(
            model_name='renditionpreset',
            name='width',
            field=models.IntegerField(blank=True, help_text='Maximum width in pixels (None for auto)', null=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='downloads_count',
            field=models.IntegerField(default=0, help_text='Current downloads count'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration date and time', null=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last access timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='max_downloads',
            field=models.IntegerField(blank=True, help_text='Maximum downloads allowed for this link', null=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Specific recipient (None for general link)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.recipient'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='token',
            field=models.CharField(default='', help_text='Unique access token', max_length=64, unique=True),
        ),
    ]
