# Generated by Django 3.2.23 on 2025-12-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mayan.apps.storage.classes


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0009_auto_20251024_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedrendition',
            name='file',
            field=models.FileField(blank=True, help_text='Generated rendition file', null=True, storage=mayan.apps.storage.classes.DefinedStorageLazy(name='distribution__renditions'), upload_to='renditions/distribution/'),
        ),
        migrations.CreateModel(
            name='DistributionCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the campaign', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the campaign')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', help_text='State of the campaign', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, help_text='Start datetime of the campaign', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='End datetime of the campaign', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional campaign configuration and metadata', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Owner of this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='distribution_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribution Campaign',
                'verbose_name_plural': 'Distribution Campaigns',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, help_text='Optional platform name for this campaign-publication link', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordering of this publication inside the campaign')),
                ('metadata', models.JSONField(blank=True, help_text='Additional settings for this publication in the campaign', null=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this publication belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_publications', to='distribution.distributioncampaign')),
                ('publication', models.ForeignKey(help_text='Publication that is part of the campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='distribution.publication')),
            ],
            options={
                'verbose_name': 'Campaign Publication',
                'verbose_name_plural': 'Campaign Publications',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('campaign', 'publication')},
            },
        ),
    ]
