# Generated by Django 3.2.23 on 2025-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_auto_20251222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='allow_download',
            field=models.BooleanField(default=True, help_text='Allow downloading files from this link'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='max_views',
            field=models.IntegerField(blank=True, help_text='Maximum views allowed for this link', null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Hashed password for link protection', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Current views count'),
        ),
    ]
