// @ts-nocheck
/**
 * Document Adapter - Bridge between Mayan EDMS API and Vue Frontend
 * ===================================================================
 * 
 * This adapter transforms Mayan EDMS Document responses into Frontend Asset format.
 * It handles null checks, URL generation, and data normalization.
 * 
 * Backend API endpoints:
 * - /api/v4/documents/ - Standard document list
 * - /digital-assets/api/documents/ - DAM enriched list (with AI analysis)
 * - /api/v4/document_files/{id}/download/ - File download URL
 * 
 * @module documentAdapter
 */

import type { Asset, AIAnalysis, Comment, Version } from '@/types/api'

// ============================================================================
// MAYAN EDMS API TYPES (based on swagger.json)
// ============================================================================

/**
 * Mayan EDMS Document response from /api/v4/documents/
 */
export interface MayanDocument {
  id: number
  uuid: string
  label: string
  description: string
  datetime_created: string // ISO 8601
  document_type: {
    id: number
    label: string
    url?: string
  }
  file_latest?: MayanDocumentFile
  files_count?: number
  files?: MayanDocumentFile[]
  url?: string
  // DAM-specific fields (from /digital-assets/api/documents/)
  ai_analysis?: MayanAIAnalysis
  metadata?: MayanMetadataValue[]
  tags?: MayanTag[]
  cabinets?: MayanCabinet[]
}

/**
 * Mayan Document File (attached to document)
 */
export interface MayanDocumentFile {
  id: number
  document: number // document_id
  encoding?: string
  filename: string
  mimetype: string
  size: number
  timestamp: string // ISO 8601
  checksum?: string
  download_url: string
  pages_url?: string
  pages_count?: number
  // Preview URLs (generated by converter app)
  preview_url?: string
  thumbnail_url?: string
}

/**
 * Mayan Document Version
 */
export interface MayanDocumentVersion {
  id: number
  document: number
  timestamp: string
  comment?: string
  active: boolean
  pages_count?: number
  export_url?: string
}

/**
 * Mayan AI Analysis (from DAM module)
 */
export interface MayanAIAnalysis {
  id?: number
  document?: number
  ai_description?: string
  ai_tags?: string[]
  categories?: string[]
  people?: string[]
  locations?: string[]
  dominant_colors?: string[]
  copyright_notice?: string
  analysis_status?: 'pending' | 'processing' | 'completed' | 'failed'
  ai_provider?: string
  confidence?: number
  created?: string
  updated?: string
}

/**
 * Mayan Metadata Value
 */
export interface MayanMetadataValue {
  id: number
  document: number
  metadata_type: {
    id: number
    name: string
    label: string
    default?: string
  }
  value: string
}

/**
 * Mayan Tag
 */
export interface MayanTag {
  id: number
  label: string
  color: string
  url?: string
}

/**
 * Mayan Cabinet (folder)
 */
export interface MayanCabinet {
  id: number
  label: string
  full_path: string
  parent?: number
}

/**
 * Mayan Paginated Response
 */
export interface MayanPaginatedResponse<T> {
  count: number
  next: string | null
  previous: string | null
  results: T[]
}

// ============================================================================
// ADAPTER CONFIGURATION
// ============================================================================

/**
 * Adapter configuration options
 */
export interface DocumentAdapterConfig {
  /** Base URL for API (e.g., 'http://localhost:8080') */
  baseUrl?: string
  /** Default thumbnail URL when file_latest is missing */
  placeholderThumbnail?: string
  /** S3 URL map for mock-to-S3 bridge */
  s3UrlMap?: Record<string, string>
  /** Whether to use S3 URLs for thumbnails */
  useS3Thumbnails?: boolean
}

// Default configuration
const defaultConfig: DocumentAdapterConfig = {
  baseUrl: '',
  placeholderThumbnail: '/placeholder-document.svg',
  useS3Thumbnails: false,
}

// Global adapter config (can be set via setAdapterConfig)
let adapterConfig: DocumentAdapterConfig = { ...defaultConfig }

/**
 * Set global adapter configuration
 */
export function setAdapterConfig(config: Partial<DocumentAdapterConfig>): void {
  adapterConfig = { ...adapterConfig, ...config }
}

/**
 * Get current adapter configuration
 */
export function getAdapterConfig(): DocumentAdapterConfig {
  return { ...adapterConfig }
}

// ============================================================================
// URL HELPERS
// ============================================================================

/**
 * Generate full URL from relative path
 */
function toFullUrl(path: string | undefined): string | undefined {
  if (!path) return undefined
  if (path.startsWith('http://') || path.startsWith('https://')) {
    return path
  }
  return `${adapterConfig.baseUrl}${path}`
}

/**
 * Generate thumbnail URL for document
 * Priority: S3 map → file_latest.thumbnail_url → file_latest.download_url → placeholder
 */
function getThumbnailUrl(doc: MayanDocument): string {
  // 1. Check S3 URL map (for mock-to-S3 bridge)
  if (adapterConfig.useS3Thumbnails && adapterConfig.s3UrlMap) {
    // Try to find matching S3 URL by document ID or label
    const s3Key = `asset_${doc.id}`
    if (adapterConfig.s3UrlMap[s3Key]) {
      return adapterConfig.s3UrlMap[s3Key]
    }
  }

  // 2. Use file_latest thumbnail
  if (doc.file_latest?.thumbnail_url) {
    return toFullUrl(doc.file_latest.thumbnail_url) || adapterConfig.placeholderThumbnail!
  }

  // 3. Use file_latest preview (lower priority)
  if (doc.file_latest?.preview_url) {
    return toFullUrl(doc.file_latest.preview_url) || adapterConfig.placeholderThumbnail!
  }

  // 4. Construct thumbnail URL from download_url (Mayan convention)
  if (doc.file_latest?.download_url) {
    // Mayan generates thumbnails at /documents/{id}/pages/{page_num}/image/
    // But for simplicity, we use download URL as fallback
    return toFullUrl(doc.file_latest.download_url) || adapterConfig.placeholderThumbnail!
  }

  // 5. Fallback to placeholder
  return adapterConfig.placeholderThumbnail!
}

/**
 * Generate preview URL for document
 */
function getPreviewUrl(doc: MayanDocument): string | undefined {
  if (doc.file_latest?.preview_url) {
    return toFullUrl(doc.file_latest.preview_url)
  }
  if (doc.file_latest?.download_url) {
    return toFullUrl(doc.file_latest.download_url)
  }
  return undefined
}

// ============================================================================
// MIME TYPE HELPERS
// ============================================================================

/**
 * Determine asset type from MIME type
 */
function getAssetType(mimeType: string | undefined): string {
  if (!mimeType) return 'document'
  
  if (mimeType.startsWith('image/')) return 'image'
  if (mimeType.startsWith('video/')) return 'video'
  if (mimeType.startsWith('audio/')) return 'audio'
  if (mimeType === 'application/pdf') return 'document'
  if (mimeType.includes('spreadsheet') || mimeType.includes('excel')) return 'document'
  if (mimeType.includes('presentation') || mimeType.includes('powerpoint')) return 'document'
  if (mimeType.includes('document') || mimeType.includes('word')) return 'document'
  
  return 'document'
}

// ============================================================================
// MAIN ADAPTER FUNCTIONS
// ============================================================================

/**
 * Transform Mayan AI Analysis to Frontend AI Analysis
 */
export function adaptAIAnalysis(mayanAI: MayanAIAnalysis | undefined): AIAnalysis | undefined {
  if (!mayanAI) return undefined

  const status = mayanAI.analysis_status || 'pending'
  
  return {
    status: status as AIAnalysis['status'],
    tags: mayanAI.ai_tags,
    ai_description: mayanAI.ai_description,
    colors: mayanAI.dominant_colors,
    confidence: mayanAI.confidence,
    provider: mayanAI.ai_provider,
    // Map detected objects from categories/people if available
    objects_detected: [
      ...(mayanAI.categories || []).map(cat => ({
        name: cat,
        confidence: 0.85,
      })),
      ...(mayanAI.people || []).map(person => ({
        name: person,
        confidence: 0.9,
      })),
    ].slice(0, 10), // Limit to 10 objects
  }
}

/**
 * Transform Mayan Document to Frontend Asset
 */
export function adaptDocument(doc: MayanDocument): Asset {
  const mimeType = doc.file_latest?.mimetype || 'application/octet-stream'
  const assetType = getAssetType(mimeType)

  // Extract tags from various sources
  const tags: string[] = [
    ...(doc.tags?.map(t => t.label) || []),
    ...(doc.ai_analysis?.ai_tags || []),
  ]
  // Remove duplicates
  const uniqueTags = [...new Set(tags)]

  // Build metadata from Mayan metadata values
  const metadata: Record<string, unknown> = {
    type: assetType,
    status: 'approved', // Default status (could be enhanced with workflow state)
  }
  
  // Add document type info
  if (doc.document_type) {
    metadata.document_type = doc.document_type.label
    metadata.document_type_id = doc.document_type.id
  }

  // Add metadata values
  if (doc.metadata) {
    for (const mv of doc.metadata) {
      metadata[mv.metadata_type.name] = mv.value
    }
  }

  // Add dimensions for images/videos (if available in metadata)
  if (assetType === 'image' || assetType === 'video') {
    // These would come from AI analysis or metadata
    if (doc.ai_analysis?.categories?.includes('landscape')) {
      metadata.width = 1920
      metadata.height = 1080
    }
  }

  return {
    id: doc.id,
    label: doc.label,
    filename: doc.file_latest?.filename || doc.label,
    size: doc.file_latest?.size || 0,
    mime_type: mimeType,
    date_added: doc.datetime_created,
    thumbnail_url: getThumbnailUrl(doc),
    preview_url: getPreviewUrl(doc),
    tags: uniqueTags,
    metadata,
    ai_analysis: adaptAIAnalysis(doc.ai_analysis),
    access_level: 'internal', // Default access level
    file_details: doc.file_latest ? {
      filename: doc.file_latest.filename,
      size: doc.file_latest.size,
      mime_type: doc.file_latest.mimetype,
      uploaded_date: doc.file_latest.timestamp,
      checksum: doc.file_latest.checksum,
    } : undefined,
  }
}

/**
 * Transform array of Mayan Documents to Frontend Assets
 */
export function adaptDocuments(docs: MayanDocument[]): Asset[] {
  return docs.map(adaptDocument)
}

/**
 * Transform Mayan paginated response to Frontend paginated response
 */
export function adaptPaginatedResponse(
  response: MayanPaginatedResponse<MayanDocument>
): {
  count: number
  next: string | null
  previous: string | null
  results: Asset[]
  page_size?: number
  total_pages?: number
} {
  const pageSize = response.results.length || 20
  const totalPages = Math.ceil(response.count / pageSize)

  return {
    count: response.count,
    next: response.next,
    previous: response.previous,
    results: adaptDocuments(response.results),
    page_size: pageSize,
    total_pages: totalPages,
  }
}

// ============================================================================
// REVERSE ADAPTERS (Frontend → Mayan)
// ============================================================================

/**
 * Transform Frontend Asset metadata to Mayan document update payload
 */
export function toMayanDocumentUpdate(asset: Partial<Asset>): Record<string, unknown> {
  const payload: Record<string, unknown> = {}

  if (asset.label !== undefined) {
    payload.label = asset.label
  }

  // Note: Tags and metadata require separate API calls in Mayan
  // This returns only the document-level fields

  return payload
}

/**
 * Transform Frontend tags to Mayan tag attach payload
 */
export function toMayanTagAttach(
  documentId: number,
  tagIds: number[]
): { document_ids: number[] } {
  return {
    document_ids: [documentId],
  }
}

/**
 * Transform Frontend metadata to Mayan metadata update payload
 */
export function toMayanMetadataUpdate(
  metadataTypeId: number,
  value: string
): { value: string } {
  return { value }
}

// ============================================================================
// UTILITY EXPORTS
// ============================================================================

export {
  getThumbnailUrl,
  getPreviewUrl,
  getAssetType,
  toFullUrl,
}

// ============================================================================
// TYPE EXPORTS
// ============================================================================

export type {
  MayanDocument,
  MayanDocumentFile,
  MayanDocumentVersion,
  MayanAIAnalysis,
  MayanMetadataValue,
  MayanTag,
  MayanCabinet,
  MayanPaginatedResponse,
}

