# Generated by Django 3.2.23 on 2025-11-10 11:51

from django.db import migrations, models
import django.db.models.deletion
import mayan.apps.databases.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0080_populate_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAMMetadataPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the metadata preset', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of this preset', verbose_name='Description')),
                ('ai_providers', models.JSONField(default=dict, help_text='AI providers configuration as JSON', verbose_name='AI Providers')),
                ('extract_description', models.BooleanField(default=True, help_text='Extract AI description', verbose_name='Extract Description')),
                ('extract_tags', models.BooleanField(default=True, help_text='Extract AI tags', verbose_name='Extract Tags')),
                ('extract_colors', models.BooleanField(default=True, help_text='Extract dominant colors', verbose_name='Extract Colors')),
                ('extract_alt_text', models.BooleanField(default=True, help_text='Generate alt text', verbose_name='Extract Alt Text')),
                ('supported_mime_types', models.JSONField(default=list, help_text='Supported MIME types as JSON array', verbose_name='Supported MIME Types')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this preset is enabled', verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'DAM Metadata Preset',
                'verbose_name_plural': 'DAM Metadata Presets',
            },
        ),
        migrations.CreateModel(
            name='DocumentAIAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_description', models.TextField(blank=True, help_text='AI-generated description of the document content', null=True, verbose_name='AI Description')),
                ('ai_tags', models.JSONField(blank=True, help_text='AI-generated tags as JSON array', null=True, verbose_name='AI Tags')),
                ('dominant_colors', models.JSONField(blank=True, help_text='Dominant colors extracted by AI', null=True, verbose_name='Dominant Colors')),
                ('alt_text', models.CharField(blank=True, help_text='AI-generated alt text for accessibility', max_length=255, null=True, verbose_name='Alt Text')),
                ('ai_provider', models.CharField(blank=True, help_text='AI provider used for analysis', max_length=50, verbose_name='AI Provider')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of AI analysis', max_length=20, verbose_name='Analysis Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis_completed', models.DateTimeField(blank=True, help_text='When AI analysis was completed', null=True, verbose_name='Analysis Completed')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document AI Analysis',
                'verbose_name_plural': 'Document AI Analyses',
            },
            bases=(mayan.apps.databases.model_mixins.ExtraDataModelMixin, models.Model),
        ),
    ]
