# Generated by Django 3.2.23 on 2025-12-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0004_processing_status_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentaianalysis',
            name='dam_ai_task_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentaianalysis',
            name='dam_ai_status_idx',
        ),
    ]
