# Generated by Django 3.2.23 on 2025-10-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0055_auto_20200814_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_checksum', models.CharField(blank=True, max_length=64, verbose_name='Исходный checksum')),
                ('edited_checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum после редактирования')),
                ('status', models.CharField(choices=[('editing', 'Редактируется'), ('saved', 'Сохранено'), ('cancelled', 'Отменено')], default='editing', max_length=32, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_edit_sessions', to='documents.documentfile', verbose_name='Файл документа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_edit_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия редактирования изображения',
                'verbose_name_plural': 'Сессии редактирования изображений',
            },
        ),
        migrations.CreateModel(
            name='ImageEditOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('crop', 'Обрезка'), ('rotate', 'Поворот'), ('flip', 'Отражение'), ('brightness', 'Яркость'), ('contrast', 'Контраст'), ('draw', 'Рисование'), ('text', 'Текст'), ('filter', 'Фильтр')], max_length=32, verbose_name='Тип операции')),
                ('parameters', models.JSONField(verbose_name='Параметры операции')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='image_editor.imageeditsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Операция редактирования изображения',
                'verbose_name_plural': 'Операции редактирования изображения',
                'ordering': ('order', 'created'),
            },
        ),
    ]
