/**
 * S3 URL Provider for Mock Data
 * ==============================
 * 
 * Provides S3 URLs for mock assets when available.
 * Falls back to Unsplash URLs when S3 map is not populated.
 * 
 * Usage:
 *   import { getS3ImageUrl, isS3Available } from '@/mocks/s3Provider'
 *   
 *   const thumbnailUrl = getS3ImageUrl('landscape_01') || FALLBACK_URL
 */

// Import S3 map (generated by scripts/migrate_mocks.py)
import s3Map from './s3_map.json'

// ============================================================================
// TYPES
// ============================================================================

export interface S3Asset {
  id: string
  label: string
  type: string
  s3_key: string
  s3_url: string
  original_url: string
  size_bytes: number
}

export interface S3Map {
  generated_at: string
  bucket: string
  endpoint: string
  prefix: string
  total_count: number
  total_size_bytes: number
  assets: Record<string, S3Asset>
  url_map: Record<string, string>
  _note?: string
}

// ============================================================================
// S3 MAP ACCESSOR
// ============================================================================

// Type cast the imported JSON
const typedS3Map = s3Map as S3Map

/**
 * Check if S3 assets are available (map has been populated)
 * Note: In "direct_unsplash" mode, URLs point to Unsplash CDN for development.
 * In production, they will point to actual S3 bucket.
 */
export function isS3Available(): boolean {
  return typedS3Map.total_count > 0
}

/**
 * Check if we're using direct Unsplash URLs (development mode)
 */
export function isUsingDirectUrls(): boolean {
  return (typedS3Map as any).mode === 'direct_unsplash'
}

/**
 * Get S3 URL for asset by ID
 * @returns S3 URL or undefined if not available
 */
export function getS3ImageUrl(assetId: string): string | undefined {
  return typedS3Map.url_map[assetId]
}

/**
 * Get full S3 asset info by ID
 */
export function getS3Asset(assetId: string): S3Asset | undefined {
  return typedS3Map.assets[assetId]
}

/**
 * Get all S3 URLs as array
 */
export function getAllS3Urls(): string[] {
  return Object.values(typedS3Map.url_map)
}

/**
 * Get S3 map metadata
 */
export function getS3MapMeta(): {
  bucket: string
  endpoint: string
  prefix: string
  totalCount: number
  totalSizeBytes: number
  generatedAt: string
} {
  return {
    bucket: typedS3Map.bucket,
    endpoint: typedS3Map.endpoint,
    prefix: typedS3Map.prefix,
    totalCount: typedS3Map.total_count,
    totalSizeBytes: typedS3Map.total_size_bytes,
    generatedAt: typedS3Map.generated_at,
  }
}

// ============================================================================
// FALLBACK URL MAPS
// ============================================================================

/**
 * Unsplash fallback URLs (used when S3 is not available)
 */
export const UNSPLASH_FALLBACK_URLS: Record<string, string> = {
  // Landscape images
  'landscape_01': 'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=1200&h=900&fit=crop',
  'landscape_02': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=900&fit=crop',
  'landscape_03': 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=900&fit=crop',
  'landscape_04': 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1200&h=900&fit=crop',
  'landscape_05': 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=1200&h=900&fit=crop',
  'landscape_06': 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=900&fit=crop',
  'landscape_07': 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&h=900&fit=crop',
  'landscape_08': 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=900&fit=crop',
  'landscape_09': 'https://images.unsplash.com/photo-1518173946687-a4c036bc4f9a?w=1200&h=900&fit=crop',
  'landscape_10': 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1200&h=900&fit=crop',
  // Portrait images
  'portrait_01': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&h=1200&fit=crop',
  'portrait_02': 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900&h=1200&fit=crop',
  'portrait_03': 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=900&h=1200&fit=crop',
  'portrait_04': 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=900&h=1200&fit=crop',
  'portrait_05': 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=900&h=1200&fit=crop',
  // Video thumbnails
  'video_01': 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=1200&h=900&fit=crop',
  'video_02': 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=900&fit=crop',
  'video_03': 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&h=900&fit=crop',
  // Document thumbnail
  'document_01': 'https://images.unsplash.com/photo-1568667256549-094345857637?w=1200&h=900&fit=crop',
  // Additional
  'architecture_01': 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&h=900&fit=crop',
  'technology_01': 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=900&fit=crop',
  'food_01': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&h=900&fit=crop',
  'business_01': 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1200&h=900&fit=crop',
  'abstract_01': 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=1200&h=900&fit=crop',
  'city_01': 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=1200&h=900&fit=crop',
}

/**
 * Get image URL with S3 priority, Unsplash fallback
 * @param assetId Asset ID (e.g., 'landscape_01')
 * @returns URL (S3 if available, otherwise Unsplash)
 */
export function getImageUrl(assetId: string): string {
  // Priority: S3 → Unsplash fallback
  return getS3ImageUrl(assetId) || UNSPLASH_FALLBACK_URLS[assetId] || ''
}

/**
 * Get random image URL from available pool
 * @param type Optional filter by type prefix ('landscape', 'portrait', 'video', 'document')
 */
export function getRandomImageUrl(type?: string): string {
  let keys = Object.keys(UNSPLASH_FALLBACK_URLS)
  
  if (type) {
    keys = keys.filter(key => key.startsWith(type))
  }
  
  if (keys.length === 0) {
    keys = Object.keys(UNSPLASH_FALLBACK_URLS)
  }
  
  const randomKey = keys[Math.floor(Math.random() * keys.length)]
  return getImageUrl(randomKey!)
}

/**
 * Get array of all available image URLs
 */
export function getAllImageUrls(): string[] {
  if (isS3Available()) {
    return getAllS3Urls()
  }
  return Object.values(UNSPLASH_FALLBACK_URLS)
}

// ============================================================================
// INDEX-BASED ACCESS (for mock asset generation)
// ============================================================================

// Ordered array of asset IDs for index-based access
const ORDERED_ASSET_IDS = [
  'landscape_01', 'landscape_02', 'landscape_03', 'landscape_04', 'landscape_05',
  'landscape_06', 'landscape_07', 'landscape_08', 'landscape_09', 'landscape_10',
  'portrait_01', 'portrait_02', 'portrait_03', 'portrait_04', 'portrait_05',
  'video_01', 'video_02', 'video_03',
  'document_01',
  'architecture_01', 'technology_01', 'food_01', 'business_01', 'abstract_01', 'city_01',
]

/**
 * Get image URL by numeric index (wraps around)
 * @param index Numeric index
 * @returns Image URL
 */
export function getImageUrlByIndex(index: number): string {
  const assetId = ORDERED_ASSET_IDS[index % ORDERED_ASSET_IDS.length]!
  return getImageUrl(assetId)
}

/**
 * Get total count of available images
 */
export function getTotalImageCount(): number {
  return ORDERED_ASSET_IDS.length
}

// ============================================================================
// EXPORTS
// ============================================================================

export default {
  isS3Available,
  getS3ImageUrl,
  getS3Asset,
  getAllS3Urls,
  getS3MapMeta,
  getImageUrl,
  getRandomImageUrl,
  getAllImageUrls,
  getImageUrlByIndex,
  getTotalImageCount,
  UNSPLASH_FALLBACK_URLS,
}

